# Generated by Django 4.2.4 on 2023-11-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("card", "0004_alter_card_box"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="question",
            field=models.CharField(
                choices=[
                    ("FR", "Freshman"),
                    ("SO", "Sophomore"),
                    ("JR", "Junior"),
                    ("SR", "Senior"),
                    ("GR", "Graduate"),
                ],
                max_length=100,
            ),
        ),
    ]
