# Generated by Django 4.2.4 on 2023-11-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("card", "0005_alter_card_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="question",
            field=models.CharField(max_length=100),
        ),
    ]
